version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: elasticsearch-model
    versions:
    - ">= 7.a, < 8"
  - dependency-name: sidekiq
    versions:
    - ">= 6.1.a, < 6.2"
  - dependency-name: coffee-rails
    versions:
    - 5.0.0
  - dependency-name: listen
    versions:
    - 3.4.1
  - dependency-name: sdoc
    versions:
    - 2.0.4
  - dependency-name: goldiloader
    versions:
    - 4.0.0
  - dependency-name: exception_notification
    versions:
    - 4.4.3
  - dependency-name: graphql
    versions:
    - 1.12.3
  - dependency-name: bullet
    versions:
    - 6.1.3
  - dependency-name: foreman
    versions:
    - 0.87.2
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
