name: Deploy staging

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          # Name of the variable configured in Secrets of our GitHub organisation
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add server to known_hosts
        run: ssh-keyscan -p 22 -H app.media.test.c3voc.de >> ~/.ssh/known_hosts
      - name: Deploy
        env:
          CAP_REPO: https://github.com/voc/voctoweb.git
          CAP_USER: media
          CAP_BRANCH: ${{ github.ref_name }}
          CAP_HOST: app.media.test.c3voc.de
          CAP_PORT: 22
          SKIP_TAG: "true"
        run: bundle exec cap staging deploy
